// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/goriller/ginny"
	"github.com/goriller/ginny-broker"
	config2 "github.com/goriller/ginny-demo/internal/config"
	"github.com/goriller/ginny-demo/internal/repo"
	"github.com/goriller/ginny-demo/internal/service"
	"github.com/goriller/ginny-demo/internal/task"
	"github.com/goriller/ginny-mysql"
	"github.com/goriller/ginny/config"
	"github.com/goriller/ginny/logger"
	"github.com/goriller/ginny/server"
)

import (
	_ "go.uber.org/automaxprocs/maxprocs"
)

// Injectors from app.go:

// NewApp
func NewApp(ctx context.Context) (*ginny.Application, error) {
	viper, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	option, err := ginny.NewOption(viper)
	if err != nil {
		return nil, err
	}
	zapLogger := logger.Default()
	configConfig, err := config2.NewConfig(viper)
	if err != nil {
		return nil, err
	}
	brokerConfig, err := broker.NewConfiguration(viper)
	if err != nil {
		return nil, err
	}
	brokerBroker, err := broker.NewBroker(ctx, zapLogger, brokerConfig)
	if err != nil {
		return nil, err
	}
	taskTask := &task.Task{
		Broker: brokerBroker,
	}
	mysqlConfig, err := mysql.NewConfig(viper)
	if err != nil {
		return nil, err
	}
	sqlBuilder, err := mysql.NewSqlBuilder(ctx, mysqlConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	userRepo := repo.NewUserRepo(configConfig, sqlBuilder)
	serviceService, err := service.NewService(ctx, configConfig, taskTask, userRepo)
	if err != nil {
		return nil, err
	}
	registrarFunc := service.RegisterService(ctx, serviceService)
	v := serverOption()
	application, err := ginny.NewApp(ctx, option, zapLogger, registrarFunc, v...)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// app.go:

func serverOption() (opts []server.Option) {

	return
}
