app:
  name: github.com/goriller/ginny-demo
  Version: 0.0.1
  GrpcAddr: :9000
  HttpAddr: :8080
config:
  test: json
consul:
  address: ${consul_addr}
jaeger:
  serviceName: test
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
