app:
  name: github.com/goriller/ginny-demo
config:
  provider: #remote config provider: etcd、consul
  endpoint:
  path:
  types: json
http:
  mode: release
  host: 127.0.0.1
  port: 9090
grpc:
  host:
  port: 9000
consul:
  address: ${consul_addr}
jaeger:
  serviceName: test
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
mysql:
  db_name: test
  wdb:
    host: ${mysql_host}
    user: ${mysql_user}
    pass: ${mysql_pass}
  rdbs:
    - host: ${mysql_host}
      user: ${mysql_user}
      pass: ${mysql_pass}
